+ echo Logging output to kitti/logs/kitti_car_3DOP_top2K_vgg16.txt.2018-02-21_20-35-23
Logging output to kitti/logs/kitti_car_3DOP_top2K_vgg16.txt.2018-02-21_20-35-23
+ ./tools/train_net.py --gpu 0 --solver kitti/models/kitti_car/VGG16/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb kitti_car_train --cfg kitti/cfgs/kitti_car_3DOP_top2K.yml
Called with args:
Namespace(cfg_file='kitti/cfgs/kitti_car_3DOP_top2K.yml', gpu_id=0, imdb_name='kitti_car_train', max_iters=40000, pretrained_model='data/imagenet_models/VGG16.v2.caffemodel', randomize=False, solver='kitti/models/kitti_car/VGG16/solver.prototxt')
Error under config key: TEST
Traceback (most recent call last):
  File "./tools/train_net.py", line 63, in <module>
    cfg_from_file(args.cfg_file)
  File "/home/rajatmittal/Documents/stereo-image-paper-implementation/3DOP_code_cuDNNv5/frcn-kitti/tools/../lib/fast_rcnn/config.py", line 179, in cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/home/rajatmittal/Documents/stereo-image-paper-implementation/3DOP_code_cuDNNv5/frcn-kitti/tools/../lib/fast_rcnn/config.py", line 166, in _merge_a_into_b
    _merge_a_into_b(a[k], b[k])
  File "/home/rajatmittal/Documents/stereo-image-paper-implementation/3DOP_code_cuDNNv5/frcn-kitti/tools/../lib/fast_rcnn/config.py", line 155, in _merge_a_into_b
    raise KeyError('{} is not a valid config key'.format(k))
KeyError: 'PROPOSAL_METHOD is not a valid config key'
